import * as motion from 'motion/react-client'
import { useRef } from 'react'

export const Hero = () => {
  const secondSectionRef = useRef<HTMLDivElement>(null)
  const contentRef = useRef<HTMLDivElement>(null)

  return (
    <motion.section
      ref={secondSectionRef}
      className="sticky top-0 flex h-screen w-full snap-start flex-col items-center justify-center overflow-hidden bg-white"
    >
      <nav className="absolute top-0 right-0 left-0 z-50 flex items-center justify-between px-8 py-6">
        <div className="flex items-center space-x-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#f54a00]">
            <span className="text-sm font-bold text-white">🍳</span>
          </div>
          <span className="text-2xl font-bold text-black">ChefAI</span>
        </div>
        <div className="hidden items-center space-x-8 md:flex">
          <a
            href="#"
            className="text-zinc-700 transition-colors hover:text-black"
          >
            Inicio
          </a>
          <a
            href="#"
            className="flex items-center text-zinc-700 transition-colors hover:text-black"
          >
            Funciones
          </a>
          <a
            href="#"
            className="flex items-center text-zinc-700 transition-colors hover:text-black"
          >
            Recetas
          </a>
          <a
            href="#"
            className="flex items-center text-zinc-700 transition-colors hover:text-black"
          >
            Nosotros
          </a>
        </div>
        <button className="rounded-lg bg-[#f54a00] px-6 py-3 font-semibold text-white transition-colors hover:bg-[#f54a00]">
          Probar Gratis
        </button>
      </nav>
      <div ref={contentRef} className="mx-auto max-w-4xl px-8 text-center">
        <h1 className="mb-8 text-6xl leading-tight font-bold text-black md:text-7xl">
          Cocina inteligente con
          <br />
          <span className="text-black">IA personalizada</span>
        </h1>
        <p className="mx-auto mb-12 max-w-3xl text-xl leading-relaxed text-zinc-600 md:text-2xl">
          Descubre recetas perfectas adaptadas a tus ingredientes, preferencias
          y restricciones. ChefAI transforma la forma en que cocinas con
          inteligencia artificial avanzada.
        </p>
        <button className="mb-16 rounded-lg bg-[#f54a00] px-8 py-4 text-lg font-semibold text-white transition-colors hover:bg-[#f54a00]">
          Generar mi primera receta
        </button>
      </div>
      <div className="absolute right-0 bottom-16 left-0 flex items-center justify-center space-x-6 opacity-90">
        <div className="h-32 w-48 rotate-6 transform overflow-hidden rounded-xl border border-zinc-100 bg-white shadow-xl transition-transform duration-300 hover:rotate-3">
          <div className="flex h-full flex-col justify-between p-4">
            <div className="flex items-center space-x-2">
              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-orange-100">
                <span className="text-sm">🥕</span>
              </div>
              <div>
                <div className="text-sm font-semibold text-zinc-800">
                  Pasta con Verduras
                </div>
                <div className="text-xs text-zinc-500">25 min • 4 personas</div>
              </div>
            </div>
            <div className="flex items-center justify-between">
              <div className="text-xs text-zinc-400">Generated by AI</div>
              <div className="flex space-x-1">
                <span className="text-xs">⭐</span>
                <span className="text-xs font-medium">4.8</span>
              </div>
            </div>
          </div>
        </div>
        <div className="h-36 w-52 -rotate-3 transform rounded-xl border border-zinc-700 bg-gradient-to-br from-zinc-900 to-zinc-800 shadow-xl transition-transform duration-300 hover:rotate-0">
          <div className="flex h-full flex-col justify-between p-4 text-white">
            <div className="flex items-center space-x-2">
              <div className="h-2 w-2 animate-pulse rounded-full bg-[#f54a00]"></div>
              <span className="text-sm font-semibold">
                Análisis Nutricional
              </span>
            </div>
            <div className="space-y-2">
              <div className="flex justify-between text-xs">
                <span>Calorías</span>
                <span className="font-medium">485 kcal</span>
              </div>
              <div className="flex justify-between text-xs">
                <span>Proteínas</span>
                <span className="font-medium">28g</span>
              </div>
              <div className="h-1 w-full overflow-hidden rounded-full bg-zinc-700">
                <div className="h-full w-3/4 rounded-full bg-[#f54a00]"></div>
              </div>
            </div>
            <div className="text-xs font-medium text-[#f54a00]">
              powered by AI
            </div>
          </div>
        </div>
        <div className="h-28 w-44 rotate-2 transform rounded-xl border border-green-100 bg-gradient-to-br from-green-50 to-emerald-50 shadow-xl transition-transform duration-300 hover:rotate-1">
          <div className="flex h-full flex-col justify-between p-4">
            <div className="flex items-center space-x-2">
              <div className="flex h-6 w-6 items-center justify-center rounded-lg bg-green-100">
                <span className="text-xs">📷</span>
              </div>
              <span className="text-sm font-semibold text-zinc-800">
                Escáner IA
              </span>
            </div>
            <div className="text-xs text-zinc-600">
              Detecta ingredientes automáticamente
            </div>
            <div className="flex space-x-1">
              <div className="flex h-4 w-4 items-center justify-center rounded-full bg-orange-200">
                <span className="text-xs">🥕</span>
              </div>
              <div className="flex h-4 w-4 items-center justify-center rounded-full bg-red-200">
                <span className="text-xs">🍅</span>
              </div>
              <div className="flex h-4 w-4 items-center justify-center rounded-full bg-yellow-200">
                <span className="text-xs">🧄</span>
              </div>
            </div>
          </div>
        </div>
        <div className="h-30 w-40 -rotate-6 transform rounded-xl border border-purple-100 bg-gradient-to-br from-purple-50 to-pink-50 shadow-xl transition-transform duration-300 hover:-rotate-3">
          <div className="flex h-full flex-col justify-between p-3">
            <div className="flex items-center space-x-2">
              <span className="text-lg">👨‍🍳</span>
              <div>
                <div className="text-sm font-semibold text-zinc-800">
                  Chef IA
                </div>
                <div className="text-xs text-zinc-500">Recomendación</div>
              </div>
            </div>
            <div className="text-xs leading-tight text-zinc-600">
              "Prueba añadir un toque de limón para realzar los sabores"
            </div>
          </div>
        </div>
      </div>
    </motion.section>
  )
}
